Repository nycolasdiaas/zarea-de-risco, pull requests merged in 2024-12, with the labels that each got.

#3 feat_extracao_and_upload
  job_download_data.py
  job_upload_to_minio.py
  requirements.txt
  setup_minio.sh
Labels: enhancement

#4 Feat/add exceptions
  .flake8
  exceptions/__init__.py
  job_download_data.py
  job_upload_to_minio.py
Labels: enhancement

#5 init nlp
  notebooks/nlp_implementation.ipynb
Labels: enhancement, good first issue

#11 fix: configurações
  .gitignore
  docker-compose.yml
  job_download_data.py
  notebooks/nlp_implementation.ipynb
  run_jobs.sh
Labels: enhancement, fix

#15 Chore/add dev dependecies
  .gitignore
  backend/docker-compose.yml
  pyproject.toml
  requirements.txt
Labels: enhancement, update

#17 chore: split dev dependencies to the project dependencies
  dev-requirements.txt
  requirements.txt
Labels: fix

#20 chore: remove old requirements and update pyproject.toml adding all t…
  dev-requirements.txt
  pyproject.toml
  requirements.txt
Labels: documentation, update

#28 Feat/enhance service code
  .env.example
  backend/app.py
  backend/handle_minio/resources.py
  backend/handle_minio/services.py
  docker/backend/Dockerfile
Labels: update, refactor

#29 Feat/data processing job download
  data_processing/download/job_download.py
Labels: enhancement

#31 Feat/data processing modules download
  .env.example
  data_processing/download/compression.py
  data_processing/download/downloader.py
  data_processing/download/job_download.py
  data_processing/download/tar_utils.py
  data_processing/jobs/download_job.py
  data_processing/main.py
Labels: enhancement, update, refactor

#32 chore/delete-old_job_download
  data_processing/download/job_download.py
Labels: fix

#38 Fix/general fixes
  job_upload_to_minio.py
  notebooks/nlp_implementation.ipynb
  pyproject.toml
Labels: fix

#39 Feat/mudancas download e transform
  .gitignore
  data_processing/download/base_downloader.py
  data_processing/jobs/telegram_downloader.py
  data_processing/jobs/telegram_simple_downloader.py
  data_processing/transform/job_transform.ipynb
  data_processing/transform/job_transform.py
  data_processing/upload/upload_to_drive.py
  pyproject.toml
Labels: enhancement

#41 feat/tag_bairros_improved
  data_processing/transform/job_transform.ipynb
  data_processing/upload/upload_to_minio.py
Labels: enhancement, fix

#42 fix/add_bairro_and_fix_upload_with_parser
  data_processing/transform/job_transform.ipynb
  data_processing/upload/upload_to_minio.py
Labels: enhancement
