Repository nycolasdiaas/zarea-de-risco, pull requests merged in 2025-01, with the labels that each got.

#45 Feat/implements new endpoints
  backend/app.py
  backend/handle_minio/resources.py
  backend/handle_minio/services.py
  data_processing/transform/job_transform.ipynb
  notebooks/nlp_implementation.ipynb
  pyproject.toml
Labels: enhancement, update

#50 feat/changed_metadata_names
  data_processing/transform/job_transform.ipynb
Labels: fix

#52 Fix/opened minio connections
  backend/handle_minio/resources.py
  docker/backend/Dockerfile
Labels: fix, refactor

#60 Feat/new components
  frontend/index.html
  frontend/public/imgs/AZAREA2 1.png
  frontend/public/imgs/AZAREA2.png
  frontend/src/components/Links/index.jsx
  frontend/src/components/Logo/index.jsx
  frontend/src/components/Navbar/index.jsx
  frontend/src/components/SearchBar/index.jsx
  frontend/src/index.css
Labels: enhancement

#62 feat/increased-evaluation-metrics-_ml_nlp_model
  data_processing/transform/job_transform.ipynb
  notebooks/bairros_nlp.ipynb
  notebooks/nlp_implementation.ipynb
Labels: enhancement

#65 Enh/implements docker
  .env.example
  docker/frontend/Dockerfile
  frontend/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/dataRoutes.js
  frontend/vite.config.js
Labels: enhancement, update

#68 Feat/implements frontend
  .env.example
  backend/app.py
  backend/handle_minio/services.py
  data_processing/download/base_downloader.py
  data_processing/transform/job_transform.ipynb
  data_processing/upload/upload_to_minio.py
  docker/backend/Dockerfile
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.js
  frontend/src/routes/dataRoutes.js
  pyproject.toml
Labels: enhancement

#75 Feat/front end components
  frontend/public/imgs/Aerolandia.png
  frontend/public/imgs/Cajazeiras.png
  frontend/public/imgs/Cambeba.png
  frontend/public/imgs/Edson_Queiroz.png
  frontend/public/imgs/Jose_de_Alencar.png
  frontend/public/imgs/Lagoa_Sapiranga.png
  frontend/public/imgs/Parque_Iracema.png
  frontend/public/imgs/test1.png
  frontend/public/imgs/test2.png
  frontend/src/App.jsx
  frontend/src/components/Featured/index.jsx
  frontend/src/components/Links/index.jsx
  frontend/src/components/Neighborhood/index.jsx
  frontend/src/index.css
  frontend/src/resources/effects.js
  frontend/src/resources/funcionalidades.js
  frontend/src/services/App_old.jsx
Labels: enhancement
